ProductShop/Models/Order.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ProductShop.Models
{
    public class Order
    {
        public int? OrderId { get; set; }
        [Display(Name = "Product")]
        public int ProductId { get; set; }
        [Display(Name = "User name")]
        public int UserId { get; set; }
        [Display(Name = "Count product")]
        public int ProductCount { get; set; }
        public DateTime OrderCreateDate { get; set; }
        public Product Product { get; set; }
        public User User { get; set; }
    }
}

ProductShop/Models/OrderViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProductShop.Models
{
    public class OrderViewModel
    {
        public SelectList ProductList { get; set; }
        public SelectList UserList { get; set; }
        public Order Order { get; set; }
    }
}

ProductShop/Models/Product.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ProductShop.Models
{
    public class Product
    {

        public int? ProductId { get; set; }
        [Display(Name = "цена")]
        public decimal Price { get; set; }
        [Display(Name = "описание")]
        public string Description { get; set; }
        [Display(Name = "дата изготовления")]
        public DateTime ProductCreateDate { get; set; }
    }
}

ProductShop/Models/ProductShopContext.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace ProductShop.Models
{
    public class ProductShopContext: DbContext
    {
        public ProductShopContext() : base("ProductShopConnectionString")
        {           
        }

        public DbSet<Product> Products { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<Order> Orders { get; set; }

    }
}

ProductShop/Models/ProductShopDBinitializer.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace ProductShop.Models
{
    public class ProductShopDBinitializer : DropCreateDatabaseAlways<ProductShopContext>
    {
        protected override void Seed(ProductShopContext context)
        {
            context.Products.Add(new Product() { ProductId = 1, Description = "Cheese", Price = 5000, ProductCreateDate = DateTime.Now });
            context.Products.Add(new Product() { ProductId = 2, Description = "Milk", Price = 4000, ProductCreateDate = DateTime.Now });
            context.Products.Add(new Product() { ProductId = 3, Description = "Icecream", Price = 6000, ProductCreateDate = DateTime.Now });

            context.Users.Add(new User() {  FirstName = "Ivan", SecondName = "Ivanov", RegistrationDate = DateTime.Now, Email = "qew@qwe.by"});
            context.Users.Add(new User() {  FirstName = "Petr", SecondName = "Petrov", RegistrationDate = DateTime.Now, Email = "ewq@ewq.by"});

            //context.Orders.Add(new Order() {OrderCreateDate = DateTime.Now, User = context.Users.Find(1), UserId  = 1, OrderId = 1, Product = context.Products.Find(1), ProductCount = 4, ProductId = 1});
            //context.Orders.Add(new Order() {OrderCreateDate = DateTime.Now, User = context.Users.Find(2), UserId  = 2, OrderId = 2, Product = context.Products.Find(2), ProductCount = 2, ProductId = 2});

            base.Seed(context);
        }
    }
}

ProductShop/Models/User.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ProductShop.Models
{
    public class User
    {
        public int? UserId { get; set; }
        public string FirstName { get; set; }
        public string SecondName { get; set; }
        public DateTime RegistrationDate { get; set; }
        public string Email { get; set; }
    }
}

ProductShop/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProductShop.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

ProductShop/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProductShop.Models;

namespace ProductShop.Controllers
{
    public class OrdersController : Controller
    {
        ProductShopContext db = new ProductShopContext();
        // GET: Orders
        public ActionResult Index()
        {
            var order = db.Orders.Include(a => a.Product).Include(a => a.User);
            return View(order.ToList());
        }


        [HttpGet]
        public ActionResult EditOrder(int? id = null)
        {
            OrderViewModel orderViewModel = new OrderViewModel()
            {
                ProductList = new SelectList(db.Products.ToList(), "ProductId", "Description"),
                UserList = new SelectList(db.Users.ToList(), "UserId", "SecondName")
            };
            if (id == null)
            {
                return View(orderViewModel);
            }
            orderViewModel.Order = db.Orders.Find(id);
            return View(orderViewModel);
        }
        [HttpPost]
        public ActionResult EditOrder(Order order)
        {
            if (order.OrderId == null)
            {
                order.OrderCreateDate =  DateTime.Now;
                db.Entry(order).State = EntityState.Added;
            }
            else
            {
                order.OrderCreateDate = DateTime.Now;
                db.Entry(order).State = EntityState.Modified;
            }
            db.SaveChanges();
            return RedirectToAction("Index");
        }



        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

ProductShop/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProductShop.Models;

namespace ProductShop.Controllers
{
    public class ProductsController : Controller
    {
        private ProductShopContext db = new ProductShopContext();

        // GET: Products
        public ActionResult Index()
        {
            return View(db.Products.ToList());
        }
        [HttpGet]
        public ActionResult EditProduct(int? id = null)
        {
            if (id == null)
            {
                return View();
            }
            return View(db.Products.Find(id));
        }
        [HttpPost]
        public ActionResult EditProduct(Product product)
        {
            if (product.ProductId == null)
            {
                db.Entry(product).State = EntityState.Added;
            }
            else
            {
                db.Entry(product).State = EntityState.Modified;
            }
            db.SaveChanges();
            return RedirectToAction("Index");
        }




        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

ProductShop/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProductShop.Models;

namespace ProductShop.Controllers
{
    public class UsersController : Controller
    {
        ProductShopContext db = new ProductShopContext();
        // GET: User
        public ActionResult Index()
        {
            return View(db.Users.ToList());
        }

        public ActionResult UserOrders()
        {
            return View("Index");
        }

        [HttpGet]
        public ActionResult EditUser(int? id = null)
        {
            if (id == null)
            {
                return View();
            }
            return View(db.Users.Find(id));
        }
        [HttpPost]
        public ActionResult EditUser(User user)
        {
            if (user.UserId == null)
            {
                db.Entry(user).State = EntityState.Added;
            }
            else
            {
                db.Entry(user).State = EntityState.Modified;
            }
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

ProductShop/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ProductShop/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ProductShop/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

ProductShop/Views/Orders/EditOrder.cshtml
@using System.Web.Mvc.Html
@model ProductShop.Models.OrderViewModel
@{
    ViewBag.Title = "EditOrder";
}

<h2>EditOrder</h2>

@using (Html.BeginForm("EditOrder", "Orders", FormMethod.Post))
{
    <div>
        @Html.HiddenFor(m => m.Order.OrderId)
    </div>
    <div>
        @Html.LabelFor(m=>m.Order.ProductId)
        @Html.DropDownListFor(m => m.Order.ProductId, Model.ProductList)
    </div>
    <div>
        @Html.LabelFor(m => m.Order.UserId)
        @Html.DropDownListFor(m => m.Order.UserId, Model.UserList)
    </div>
    <div>
        @Html.LabelFor(m => m.Order.ProductCount)
        @Html.TextBoxFor(m => m.Order.ProductCount)
    </div>
    <div>
        <input type="submit" />
    </div>
}

ProductShop/Views/Orders/Index.cshtml
@model IEnumerable<ProductShop.Models.Order>
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
@Html.ActionLink("Add", "EditOrder")

<div>
    <table>
        <tr>
            <td>product</td>
            <td>user</td>
            <td>count</td>
        </tr>
        @foreach (var item in Model)
            {
            <tr>
                <td>@item.Product.Description</td>
                <td>@item.User.FirstName </td>
                <td>@item.ProductCount</td>
                <td>@Html.ActionLink("Edit", "EditOrder", new { id = item.OrderId })</td>
                <td>delete</td>
            </tr>

        }
    </table>
</div>

ProductShop/Views/Products/EditProduct.cshtml
@model ProductShop.Models.Product
@{
    var buttonName = @Model == null ? "Add" : "Edit";
    ViewBag.Title = "EditProduct";

}

<h2>EditProduct</h2>
@using (Html.BeginForm("EditProduct", "Products", FormMethod.Post))
{
    @Html.HiddenFor(m => m.ProductId)
    <div>
        @Html.LabelFor(m => m.Description)
        @Html.EditorFor(m => m.Description)
    </div>
    <div>
        @Html.LabelFor(m => m.Price)
        @Html.EditorFor(m => m.Price)
    </div>
    <div>
        @Html.LabelFor(m => m.ProductCreateDate)
        @Html.EditorFor(m => m.ProductCreateDate)
    </div>

    <div>
        <input type="submit" value="@buttonName" />
    </div>
}

ProductShop/Views/Products/Index.cshtml
@using ProductShop.Models
@model IEnumerable<ProductShop.Models.Product>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<div>

    <div>
        <table>
            <tr>
                <td>Name</td>
                <td>Price</td>
                <td>Date</td>
            </tr>
            @foreach (var product in Model)
            {
                <tr>
                    <td>@product.Description</td>
                    <td>@product.Price</td>
                    <td>@product.ProductCreateDate</td>
                    <td>@Html.ActionLink("Edit", "EditProduct", new {id = product.ProductId})</td>
                    <td>delete</td>
                </tr>

            }
        </table>
    </div>
    <div>@Html.ActionLink("Add", "EditProduct")</div>
</div>

ProductShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Домашняя страница", "Index", "Home")</li>
                    <li>@Html.ActionLink("Продукты", "Index", "Products")</li>
                    <li>@Html.ActionLink("Заказы", "Index", "Orders")</li>
                    <li>@Html.ActionLink("Пользователи", "Index", "Users")</li>

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year – приложение ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ProductShop/Views/Users/EditUser.cshtml
@{
    ViewBag.Title = "EditUser";
}

<h2>EditUser</h2>

ProductShop/Views/Users/Index.cshtml
@model IEnumerable<ProductShop.Models.User>
@{
    ViewBag.Title = "Index";
}

<h2>Index User</h2>

<div>

    <div>
        <table>
            <tr>
                <td>FirstName</td>
                <td>SecondName</td>
                <td>E-mail</td>
            </tr>
            @foreach (var user in Model)
            {
                <tr>
                    <td>@user.FirstName</td>
                    <td>@user.SecondName</td>
                    <td>@user.Email</td>
                    <td>@Html.ActionLink("Edit", "EditUser", new { id = user.UserId })</td>
                    <td>delete</td>
                    <td>@Html.ActionLink("User Ord", "UserOrders", new { id = user.UserId })</td>
                </tr>

            }
        </table>
    </div>
    <div>@Html.ActionLink("Add", "EditUser")</div>
</div>